### ISSUE TITLE
Undefined reference to `XTestFakeKeyEvent'

### ISSUE THREAD

**Issue by ericek111** [lilmayo/EkknodsAim#2]
Hello,
when I try to compile this stuff with ```-pthread -L/usr/include/X11 -lX11 -lXtst -lXext -m64 -std=c++11```, it fails and returns following errors:

```
CMakeFiles/lelmayo.dir/program.cpp.o: In function `program::bhoploop()':
program.cpp:(.text+0x814): undefined reference to `XFlush'
program.cpp:(.text+0x82c): undefined reference to `XKeysymToKeycode'
program.cpp:(.text+0x852): undefined reference to `XTestFakeKeyEvent'
program.cpp:(.text+0x898): undefined reference to `XTestFakeKeyEvent'
CMakeFiles/lelmayo.dir/program.cpp.o: In function `program::trigloop()':
program.cpp:(.text+0xd73): undefined reference to `XFlush'
program.cpp:(.text+0xd95): undefined reference to `XTestFakeButtonEvent'
program.cpp:(.text+0xddd): undefined reference to `XTestFakeButtonEvent'
CMakeFiles/lelmayo.dir/program.cpp.o: In function `program::run()':
program.cpp:(.text+0x117d): undefined reference to `XOpenDisplay'
```

What can I do, please?

Also, I am really happy to see fork of ekknod's cheatpack. I'm sure I'll learn a lot after playing a little bit with it. 

Thanks.

**Comment by ChrisVanL** [comment]
Make sure you have libx11-dev and xorg-dev

**Comment by AccSky** [comment]
Make sure you have libx11-dev and xorg-dev

**Comment by ericek111** [comment]
Got it working. You need to `apt-get install gcc-multilib g++-multilib libxtst-dev:i386 libx11-dev:i386` and change `-m64` flag to `-m32`. That worked for me and I finally compiled it.
